export const active: string;
export const downCaret: string;
export const iconlink: string;
export const pulled: string;
export const puller: string;
export const sidebar: string;
export const sidebarDashboardLink: string;
export const sidebarDefaultText: string;
export const sidebarSectionTitles: string;
